repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: mixed-line-ending
        args: ['--fix=lf']
        exclude: \.(bat|cmd|ps1)$
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format files with rustfmt.
        entry: bash -c 'cargo fmt --all -- --check || (cargo fmt --all && exit 1)'
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: cargo check --workspace
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-test
        name: cargo test
        description: Run tests.
        entry: bash -c 'DATABASE_URL=postgres://postgres:password@localhost/cdd cargo test --workspace'
        language: system
        types: [rust]
        pass_filenames: false

      - id: coverage-shields
        name: Update Coverage Shields
        description: Run tarpaulin and update README.md shields
        entry: bash -c './scripts/update_shields.sh'
        language: system
        types: [rust]
        pass_filenames: false
        always_run: true
